/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asia.ridwan.latihan2;

/**
 *
 * @author ridwan
 */
public class kalkulatorBangunDatar extends javax.swing.JFrame {

    /**
     * Creates new form kalkulatorBangunDatar
     */
    double panjang, lebar, luas, keliling, luaspersegi, kelilingpersegi, sisi, alas, tinggi, miring, diagonal1, diagonal2;
    
    public kalkulatorBangunDatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtsisipersegi = new javax.swing.JLabel();
        sisipersegi = new javax.swing.JTextField();
        txthasilpersegi = new javax.swing.JLabel();
        hasilluaspersegi = new javax.swing.JTextField();
        txtluaspersegi = new javax.swing.JLabel();
        txtkelilingpersegi = new javax.swing.JLabel();
        hasilkelilingpersegi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonpersegi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tinggiJajarGenjang = new javax.swing.JTextField();
        alasJajarGenjang = new javax.swing.JTextField();
        sisiMiringJajarGenjang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtluaspersegi1 = new javax.swing.JLabel();
        txtkelilingpersegi1 = new javax.swing.JLabel();
        hasilLuasJajarGenjang = new javax.swing.JTextField();
        hasilKelilingJajarGenjang = new javax.swing.JTextField();
        buttonJajar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        diagonal1BelahKetupat = new javax.swing.JTextField();
        diagonal2BelahKetupat = new javax.swing.JTextField();
        sisiBelahKetupat = new javax.swing.JTextField();
        buttonBelah = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtluaspersegi2 = new javax.swing.JLabel();
        txtkelilingpersegi2 = new javax.swing.JLabel();
        hasilLuasBelahKetupat = new javax.swing.JTextField();
        hasilKelilingBelahKetupat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Kalkulator Bangun Datar");

        txtsisipersegi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsisipersegi.setText("Masukkan Sisi");

        sisipersegi.setBackground(new java.awt.Color(204, 255, 255));
        sisipersegi.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txthasilpersegi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txthasilpersegi.setText("Hasil");

        hasilluaspersegi.setBackground(new java.awt.Color(204, 255, 204));
        hasilluaspersegi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hasilluaspersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilluaspersegiActionPerformed(evt);
            }
        });

        txtluaspersegi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtluaspersegi.setText("Luas");

        txtkelilingpersegi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtkelilingpersegi.setText("Keliling");

        hasilkelilingpersegi.setBackground(new java.awt.Color(204, 255, 204));
        hasilkelilingpersegi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hasilkelilingpersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilkelilingpersegiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Persegi");

        buttonpersegi.setBackground(new java.awt.Color(255, 204, 204));
        buttonpersegi.setText("Hitung");
        buttonpersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpersegiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Jajar Genjang");

        jLabel3.setText("Masukkan Tinggi");

        jLabel4.setText("Masukkan Alas");

        jLabel6.setText("Masukkan Miring");

        tinggiJajarGenjang.setBackground(new java.awt.Color(204, 255, 255));
        tinggiJajarGenjang.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        alasJajarGenjang.setBackground(new java.awt.Color(204, 255, 255));
        alasJajarGenjang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alasJajarGenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alasJajarGenjangActionPerformed(evt);
            }
        });

        sisiMiringJajarGenjang.setBackground(new java.awt.Color(204, 255, 255));
        sisiMiringJajarGenjang.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Hasil");

        txtluaspersegi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtluaspersegi1.setText("Luas");

        txtkelilingpersegi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtkelilingpersegi1.setText("Keliling");

        hasilLuasJajarGenjang.setBackground(new java.awt.Color(204, 255, 204));
        hasilLuasJajarGenjang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hasilLuasJajarGenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilLuasJajarGenjangActionPerformed(evt);
            }
        });

        hasilKelilingJajarGenjang.setBackground(new java.awt.Color(204, 255, 204));
        hasilKelilingJajarGenjang.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonJajar.setBackground(new java.awt.Color(255, 204, 204));
        buttonJajar.setText("Hitung");
        buttonJajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJajarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Belah Ketupat");

        jLabel9.setText("Masukkan Diagonal 1");

        jLabel10.setText("Masukkan Diagonal 2");

        jLabel11.setText("Masukkan Sisi");

        diagonal1BelahKetupat.setBackground(new java.awt.Color(204, 255, 255));
        diagonal1BelahKetupat.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        diagonal2BelahKetupat.setBackground(new java.awt.Color(204, 255, 255));
        diagonal2BelahKetupat.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sisiBelahKetupat.setBackground(new java.awt.Color(204, 255, 255));
        sisiBelahKetupat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sisiBelahKetupat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisiBelahKetupatActionPerformed(evt);
            }
        });

        buttonBelah.setBackground(new java.awt.Color(255, 204, 204));
        buttonBelah.setText("Hitung");
        buttonBelah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBelahActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Hasil");

        txtluaspersegi2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtluaspersegi2.setText("Luas");

        txtkelilingpersegi2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtkelilingpersegi2.setText("Keliling");

        hasilLuasBelahKetupat.setBackground(new java.awt.Color(204, 255, 204));
        hasilLuasBelahKetupat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hasilLuasBelahKetupat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilLuasBelahKetupatActionPerformed(evt);
            }
        });

        hasilKelilingBelahKetupat.setBackground(new java.awt.Color(204, 255, 204));
        hasilKelilingBelahKetupat.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(diagonal2BelahKetupat)
                                            .addComponent(sisiBelahKetupat)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(diagonal1BelahKetupat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonBelah))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtsisipersegi)
                                                .addGap(26, 26, 26))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(8, 8, 8)
                                                    .addComponent(sisiMiringJajarGenjang))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(tinggiJajarGenjang)
                                                        .addComponent(alasJajarGenjang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(sisipersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonJajar, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(buttonpersegi, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkelilingpersegi1)
                                    .addComponent(txtluaspersegi1))
                                .addGap(18, 18, 18)
                                .addComponent(hasilKelilingJajarGenjang))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txthasilpersegi)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtluaspersegi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addComponent(hasilluaspersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtkelilingpersegi)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(hasilLuasJajarGenjang, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(hasilkelilingpersegi)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkelilingpersegi2)
                                    .addComponent(txtluaspersegi2))
                                .addGap(18, 18, 18)
                                .addComponent(hasilKelilingBelahKetupat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(hasilLuasBelahKetupat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthasilpersegi)
                            .addComponent(hasilluaspersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtluaspersegi)
                            .addComponent(buttonpersegi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkelilingpersegi)
                            .addComponent(hasilkelilingpersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(buttonJajar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtluaspersegi1)
                                    .addComponent(hasilLuasJajarGenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtkelilingpersegi1)
                                    .addComponent(hasilKelilingJajarGenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(txtsisipersegi)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sisipersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tinggiJajarGenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alasJajarGenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sisiMiringJajarGenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(diagonal1BelahKetupat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBelah))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(diagonal2BelahKetupat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(sisiBelahKetupat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtluaspersegi2)
                            .addComponent(hasilLuasBelahKetupat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkelilingpersegi2)
                            .addComponent(hasilKelilingBelahKetupat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonpersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpersegiActionPerformed
        // TODO add your handling code here:
        luas = panjang*lebar;
        keliling = 2*(panjang+lebar);
        sisi = Double.parseDouble(sisipersegi.getText());
        luaspersegi = sisi*sisi;
        kelilingpersegi = 4*sisi;
        hasilluaspersegi.setText(String.valueOf(luas));
        hasilluaspersegi.setText(String.valueOf(luaspersegi));
        hasilkelilingpersegi.setText(String.valueOf(keliling));
        hasilkelilingpersegi.setText(String.valueOf(kelilingpersegi));
    }//GEN-LAST:event_buttonpersegiActionPerformed

    private void hasilluaspersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilluaspersegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilluaspersegiActionPerformed

    private void hasilkelilingpersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilkelilingpersegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilkelilingpersegiActionPerformed

    private void alasJajarGenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alasJajarGenjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alasJajarGenjangActionPerformed

    private void buttonJajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJajarActionPerformed
        // TODO add your handling code here:
        alas = Double.parseDouble(alasJajarGenjang.getText());
        tinggi = Double.parseDouble(tinggiJajarGenjang.getText());
        miring = Double.parseDouble(sisiMiringJajarGenjang.getText());
        luas = alas * tinggi;
        keliling = 2 * (alas + miring);
        hasilLuasJajarGenjang.setText(String.valueOf(luas));
        hasilKelilingJajarGenjang.setText(String.valueOf(keliling));
    }//GEN-LAST:event_buttonJajarActionPerformed

    private void buttonBelahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBelahActionPerformed
        // TODO add your handling code here:
        diagonal1 = Double.parseDouble(diagonal1BelahKetupat.getText());
        diagonal2 = Double.parseDouble(diagonal2BelahKetupat.getText());
        sisi = Double.parseDouble(sisiBelahKetupat.getText());
        luas = (diagonal1 * diagonal2) / 2;
        keliling = 4 * sisi;
        hasilLuasBelahKetupat.setText(String.valueOf(luas));
        hasilKelilingBelahKetupat.setText(String.valueOf(keliling));
    }//GEN-LAST:event_buttonBelahActionPerformed

    private void hasilLuasBelahKetupatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilLuasBelahKetupatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilLuasBelahKetupatActionPerformed

    private void hasilLuasJajarGenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilLuasJajarGenjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilLuasJajarGenjangActionPerformed

    private void sisiBelahKetupatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisiBelahKetupatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisiBelahKetupatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulatorBangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulatorBangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulatorBangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulatorBangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulatorBangunDatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alasJajarGenjang;
    private javax.swing.JButton buttonBelah;
    private javax.swing.JButton buttonJajar;
    private javax.swing.JButton buttonpersegi;
    private javax.swing.JTextField diagonal1BelahKetupat;
    private javax.swing.JTextField diagonal2BelahKetupat;
    private javax.swing.JTextField hasilKelilingBelahKetupat;
    private javax.swing.JTextField hasilKelilingJajarGenjang;
    private javax.swing.JTextField hasilLuasBelahKetupat;
    private javax.swing.JTextField hasilLuasJajarGenjang;
    private javax.swing.JTextField hasilkelilingpersegi;
    private javax.swing.JTextField hasilluaspersegi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField sisiBelahKetupat;
    private javax.swing.JTextField sisiMiringJajarGenjang;
    private javax.swing.JTextField sisipersegi;
    private javax.swing.JTextField tinggiJajarGenjang;
    private javax.swing.JLabel txthasilpersegi;
    private javax.swing.JLabel txtkelilingpersegi;
    private javax.swing.JLabel txtkelilingpersegi1;
    private javax.swing.JLabel txtkelilingpersegi2;
    private javax.swing.JLabel txtluaspersegi;
    private javax.swing.JLabel txtluaspersegi1;
    private javax.swing.JLabel txtluaspersegi2;
    private javax.swing.JLabel txtsisipersegi;
    // End of variables declaration//GEN-END:variables
}
